certsuite: process flags refactor
test-network-function/cnf-certification-test pull request #1848
Opened 2024-01-31 10:59 UTC by jmontesi

2024-01-31 15:52 UTC, sebrandon1 approved these changes

2024-01-31 16:44 UTC, bnshr requested changes

2024-02-01 09:46 UTC, jmontesi commented on pkg/certsuite/certsuite.go
> +		junitOutputFile := filepath.Join(outputFolder, junitXMLOutputFileName)
Done

2024-02-01 09:47 UTC, jmontesi commented on pkg/certsuite/certsuite.go
>  	fmt.Print("\n")
I wanted to be more explicit about the fact that I need an extra new line there.

2024-02-01 10:10 UTC, bnshr commented on pkg/certsuite/certsuite.go
>  	fmt.Print("\n")
Well, then you could add \n in the previous line if it is about nice display related topic. This line is unnecessarily piqued my interest.

2024-02-01 14:13 UTC, jmontesi commented on pkg/certsuite/certsuite.go
>  	fmt.Print("\n")
Our linter disagrees: `printf: "fmt.Println" arg list ends with redundant newline (govet)`

2024-02-01 14:43 UTC, bnshr commented
Merge it!

2024-02-01 14:43 UTC, bnshr approved these changes

2024-02-01 14:50 UTC, merged