Avoid unnecessary rebuild of the test environment
test-network-function/cnf-certification-test pull request #1919
Opened 2024-03-14 10:02 UTC by jmontesi

The logs show that the test environment is built twice before starting running the test cases.

2024-03-14 10:35 UTC, ramperher commented
> from change #1919:
> 
> * FAILURE https://www.distributed-ci.io/jobs/f4066011-5b95-45e6-9759-92c2aa22ac84/jobStates

The job is failing in the execution of tnf, so I believe this needs to be checked

2024-03-14 12:34 UTC, ramperher commented
/dci-rerun

2024-03-14 13:12 UTC, sebrandon1 approved these changes

2024-03-14 13:26 UTC, ramperher requested changes
tnf cannot be launched in our deployments, in this job: https://www.distributed-ci.io/jobs/0f0456cb-2996-4615-960f-f237cc09a5cd/files, in the Files section, you can take a look to dci-tnf-execution.log and cnf-certsuite.log to see the errors it is throwing. With this failure, this cannot be merged, else DCI jobs will all fail

2024-03-19 17:32 UTC, edcdavid approved these changes

2024-03-20 06:35 UTC, ramperher approved these changes

2024-03-20 11:13 UTC, merged